### ISSUE TITLE
[Error tooltip] why element add？it is Influencing layout

### ISSUE THREAD

**Issue by liaoliaojun** [feifang/vue-wordcloud#15]
![image](https://user-images.githubusercontent.com/22748955/60877370-41790d80-a270-11e9-804c-d1ad177e0094.png)
![image](https://user-images.githubusercontent.com/22748955/60877439-65d4ea00-a270-11e9-9f03-814e58330ccc.png)
class name conflict

**Comment by gadelkareem** [comment]
any workaround for this one?

**Comment by liaoliaojun** [comment]
This className is very prone to conflict

**Comment by mcbattirola** [comment]
> 
> 
> any workaround for this one?

This was really a problem in our application so I made a fork to fix it, you can find it here
https://github.com/mcbattirola/vue-wordcloud-tooltip-fix

But I think the best solution is a PR to fix this here

**Comment by liaoliaojun** [comment]
I agree with this idea and we will do it later, sorry
